alter table public.extinguishers
  add column if not exists serial_number text,
  add column if not exists manufacturer text,
  add column if not exists project_code text,
  add column if not exists standard_code text,
  add column if not exists manufacture_year integer,
  add column if not exists last_inspection_year integer,
  add column if not exists maintenance_level integer,
  add column if not exists gross_weight numeric(10,2),
  add column if not exists tare_weight numeric(10,2),
  add column if not exists total_weight numeric(10,2),
  add column if not exists loss_percentage numeric(5,2),
  add column if not exists pressure_value numeric(10,2),
  add column if not exists cylinder_volume numeric(10,2),
  add column if not exists charge_capacity text,
  add column if not exists maintenance_executor text,
  add column if not exists seal_number text,
  add column if not exists hydrostatic_test_reference text,
  add column if not exists rejection_pin boolean not null default false,
  add column if not exists rejection_thread boolean not null default false,
  add column if not exists rejection_valve boolean not null default false,
  add column if not exists rejection_pressure_gauge boolean not null default false,
  add column if not exists rejection_hose boolean not null default false,
  add column if not exists rejection_reason text;
